version: '3'
services:
  redis:
    image: redis
    container_name: javatesting-redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
  mysql:
    image: mysql:8.0.25
    container_name: javatesting-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1
      LANG: C.UTF-8
    ports:
      - 13306:3306
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  consul:
    image: consul
    container_name: javatesting-consul
    command: agent -server -ui -node=server-1 -bootstrap -client=0.0.0.0 -enable-script-checks
    environment:
      CONSUL_LOCAL_CONFIG: '{"acl": {"enabled" : true}}'
    ports:
      - 8500:8500
      - 8600:8600/udp
  lib:
    build: lib/.

  gateway:
    build: gateway/.
    container_name: javatesting-gateway
    environment:
      GATEWAY_PORT: 8080
      GATEWAY_REDIS_HOST: javatesting-redis
      GATEWAY_REDIS_PORT: 6379
      GATEWAY_HOSTNAME: gateway
      GATEWAY_CONSUL_HOST: javatesting-consul
      GATEWAY_CONSUL_PORT: 8500
      GATEWAY_CUSTOMER_URL: /order/create-order,/pre-deposited-account/customer/deposit
      GATEWAY_RETAIL_URL: /retail-inventory/product/add,/retail-inventory/product/increase-inventory
    ports:
      - "18000:8080"
  order:
    build: order/.
    container_name: javatesting-order
    environment:
      ORDER_PORT: 8082
      ORDER_HOSTNAME: order
      ORDER_GATEWAY_URL: http://gateway:8080
      ORDER_PRDA_HOSTNAME: pre-deposited-account
      ORDER_REA_HOSTNAME: retail-account
      ORDER_REINV_HOSTNAME: retail-inventory
      ORDER_CONSUL_HOST: javatesting-consul
      ORDER_CONSUL_PORT: 8500
      ORDER_MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_order
      ORDER_MYSQL_USERNAME: root
      ORDER_MYSQL_PASSWORD: 1
    depends_on:
      mysql:
        condition: service_healthy
  pre-deposited-account:
    build: pre-deposited-account/.
    container_name: javatesting-pre_deposited_account
    environment:
      PRDA_PORT: 8081
      PRDA_HOSTNAME: pre-deposited-account
      PRDA_REDIS_HOST: javatesting-redis
      PRDA_REDIS_PORT: 6379
      PRDA_CONSUL_HOST: javatesting-consul
      PRDA_CONSUL_PORT: 8500
      PRDA_MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_predepositedaccount
      PRDA_MYSQL_USERNAME: root
      PRDA_MYSQL_PASSWORD: 1
    depends_on:
      mysql:
        condition: service_healthy
  retail-account:
    build: retail-account/.
    container_name: javatesting-retail_account
    environment:
      REA_PORT: 8083
      REA_HOSTNAME: retail-account
      REA_GATEWAY_URL: http://gateway:8080
      REA_ORDER_HOSTNAME: order
      REA_REINV_HOSTNAME: retail-inventory
      REA_REDIS_HOST: javatesting-redis
      REA_REDIS_PORT: 6379
      REA_CONSUL_HOST: javatesting-consul
      REA_CONSUL_PORT: 8500
      REA_MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_retailaccount
      REA_MYSQL_USERNAME: root
      REA_MYSQL_PASSWORD: 1
    depends_on:
      mysql:
        condition: service_healthy
  retail-inventory:
    build: retail-inventory/.
    container_name: javatesting-retail_inventory
    environment:
      REINV_PORT: 8084
      REINV_HOSTNAME: retail-inventory
      REINV_GATEWAY_URL: http://gateway:8080
      REINV_REA_HOSTNAME: retail-account
      REINV_CONSUL_HOST: javatesting-consul
      REINV_CONSUL_PORT: 8500
      REINV_MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_retailinventory
      REINV_MYSQL_USERNAME: root
      REINV_MYSQL_PASSWORD: 1
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  cache:
    driver: local