version: '3'
services:
  redis:
    image: redis
    container_name: javatesting-redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
  mysql:
    image: mysql:8.0.25
    container_name: javatesting-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1
      LANG: C.UTF-8
    ports:
      - 13306:3306
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  consul:
    image: consul
    container_name: javatesting-consul
    command: agent -server -ui -node=server-1 -bootstrap -client=0.0.0.0 -enable-script-checks
    environment:
      CONSUL_LOCAL_CONFIG: '{"acl": {"enabled" : true}}'
    ports:
      - 8500:8500
      - 8600:8600/udp
  lib:
    build: lib/.

  gateway:
    build: gateway/.
    container_name: javatesting-gateway
    environment:
      REDIS_HOST: javatesting-redis
      REDIS_PORT: 6379
      CONSUL_HOST: javatesting-consul
      CONSUL_PORT: 8500
    ports:
      - "18000:8080"
  order:
    build: order/.
    container_name: javatesting-order
    environment:
      CONSUL_HOST: javatesting-consul
      CONSUL_PORT: 8500
      MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_order
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1
    depends_on:
      mysql:
        condition: service_healthy
  pre-deposited-account:
    build: pre-deposited-account/.
    container_name: javatesting-pre_deposited_account
    environment:
      REDIS_HOST: javatesting-redis
      REDIS_PORT: 6379
      CONSUL_HOST: javatesting-consul
      CONSUL_PORT: 8500
      MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_predepositedaccount
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1
    depends_on:
      mysql:
        condition: service_healthy
  retail-account:
    build: retail-account/.
    container_name: javatesting-retail_account
    environment:
      REDIS_HOST: javatesting-redis
      REDIS_PORT: 6379
      CONSUL_HOST: javatesting-consul
      CONSUL_PORT: 8500
      MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_retailaccount
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1
    depends_on:
      mysql:
        condition: service_healthy
  retail-inventory:
    build: retail-inventory/.
    container_name: javatesting-retail_inventory
    environment:
      REDIS_HOST: javatesting-redis
      REDIS_PORT: 6379
      CONSUL_HOST: javatesting-consul
      CONSUL_PORT: 8500
      MYSQL_URL: jdbc:mysql://javatesting-mysql:3306/retailselling_retailinventory
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1
      BASE_GATEWAY: http://gateway:8080
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  cache:
    driver: local