
server:
  port: ${REINV_PORT}
  
spring:
  application:
    name: ${REINV_HOSTNAME}
    baseUrl: ${REINV_GATEWAY_URL}
    retailAccountHostname: ${REINV_REA_HOSTNAME}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl