
server:
  port: ${REA_PORT}
  
spring:
  application:
    name: ${REA_HOSTNAME}
    baseUrl: ${REA_GATEWAY_URL}
    orderHostname: ${REA_ORDER_HOSTNAME}
    retailInventoryHostname: ${REA_REINV_HOSTNAME}
  redis:
    host: ${REA_REDIS_HOST}
    port: ${REA_REDIS_PORT}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl