
server:
  port: ${ORDER_PORT}
  
spring:
  application:
    name: ${ORDER_HOSTNAME}
    base-url: ${ORDER_GATEWAY_URL}
    preDepositedAccountHostname: ${ORDER_PRDA_HOSTNAME}
    retailAccountHostname: ${ORDER_REA_HOSTNAME}
    retailInventoryHostname: ${ORDER_REINV_HOSTNAME}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl