
server:
  port: ${GATEWAY_PORT}
  
spring:
  application:
    name: ${GATEWAY_HOSTNAME}
  redis:
    host: ${GATEWAY_REDIS_HOST}
    port: ${GATEWAY_REDIS_PORT}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: AuthenUserFilter
        - name: ModifyHeaderFilter
        