
server:
  port: ${PRDA_PORT}
  
spring:
  application:
    name: ${PRDA_HOSTNAME}
  redis:
    host: ${PRDA_REDIS_HOST}
    port: ${PRDA_REDIS_PORT}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl